[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
 name="WarsawBusAnalyzer-ls448575"
 version="1.0"
 author="Åukasz Skiba"
 author_email="ls448575@students.mimuw.edu.pl"
 description="Analyzer data from Warsaw Bus API"
 readme="README.md"
 classifiers=[
 "Programming Language :: Python :: 3",
 "License :: OSI Approved :: MIT License",
 "Operating System :: OS Independent",
 ]
dependencies = [
    "geopy~=2.4.1",
    "pandas~=2.1.4",
    "matplotlib.pyplot~=3.5.3",
    "requests~=2.31.0",
    "numpy~=.26.0",
    "datetime~=3.0",
    "folium~=0.1.5"
]
 python_requires='>=3.6'
